[phases.setup]
nixPkgs = ["python3", "ffmpeg", "nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
