services:
  - type: web
    name: bharat-ai-tutor
    env: node
    buildCommand: npm install
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
