services:
  - type: web
    name: bharat-ai-tutor
    env: node
    buildCommand: npm ci && pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
